language: python

dist: xenial
sudo: false

python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py install

script:
  - find . -type f -name "*.py" | xargs flake8

after_success:
  - python setup.py sdist bdist_wheel --universal
  - debuild -b -uc -us
